Repository vdorceus-excilys/ngAvengersFront, pull requests merged in 2019-06, with the labels that each got.

#1 Adding Header Bar to the application
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/list-company/list-company.component.html
  src/app/list-company/list-company.component.scss
  src/app/list-company/list-company.component.ts
  src/app/list-computer/list-computer.component.html
  src/app/list-computer/list-computer.component.scss
  src/app/list-computer/list-computer.component.ts
  src/index.html
  src/styles.scss
Labels: draft

#5 adding hammerjs, for touch support in material components
  package-lock.json
  package.json
Labels: bug

#6 Integration computer list with service
  src/app/list-computer/list-computer.component.html
  src/app/list-computer/list-computer.component.scss
  src/app/list-computer/list-computer.component.ts
Labels: enhancement

#15 Fix version property
  src/app/company-model.ts
  src/app/computer-model.ts
Labels: bug

#17 fixed sort in tables
  src/app/app.module.ts
Labels: bug

#18 Dialog opens only if selection
  src/app/list-company/list-company.component.ts
  src/app/list-computer/list-computer.component.ts
Labels: bug

#16 List users
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/list-users/list-users.component.html
  src/app/list-users/list-users.component.scss
  src/app/list-users/list-users.component.spec.ts
  src/app/list-users/list-users.component.ts
Labels: enhancement

#39 fixed self-delete issue, the current user is not in the list of users
  src/app/list-users/list-users.component.ts
Labels: bug
